int32 occupancy_threshold

int32 external_contour_threshold

int8 number_of_layers

float64[] transform

float64 map_origin_x

float64 map_origin_y

float64 map_resolution

float64 start_position_x

float64 start_position_y

int8 height_between_layers

float64 deposited_material_width

float64 contours_filtering_tolerance

nav_msgs/OccupancyGrid map
---
nav_msgs/Path path
geometry_msgs/Pose[] pose
