// Generated by gencpp from file relocalization_sweeper/GetRobotPoseRequest.msg
// DO NOT EDIT!


#ifndef RELOCALIZATION_SWEEPER_MESSAGE_GETROBOTPOSEREQUEST_H
#define RELOCALIZATION_SWEEPER_MESSAGE_GETROBOTPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace relocalization_sweeper
{
template <class ContainerAllocator>
struct GetRobotPoseRequest_
{
  typedef GetRobotPoseRequest_<ContainerAllocator> Type;

  GetRobotPoseRequest_()
    : img_data()  {
    }
  GetRobotPoseRequest_(const ContainerAllocator& _alloc)
    : img_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_data_type;
  _img_data_type img_data;





  typedef boost::shared_ptr< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetRobotPoseRequest_

typedef ::relocalization_sweeper::GetRobotPoseRequest_<std::allocator<void> > GetRobotPoseRequest;

typedef boost::shared_ptr< ::relocalization_sweeper::GetRobotPoseRequest > GetRobotPoseRequestPtr;
typedef boost::shared_ptr< ::relocalization_sweeper::GetRobotPoseRequest const> GetRobotPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace relocalization_sweeper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31eab76887221eac7fa22066d14ce1f1";
  }

  static const char* value(const ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31eab76887221eacULL;
  static const uint64_t static_value2 = 0x7fa22066d14ce1f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "relocalization_sweeper/GetRobotPoseRequest";
  }

  static const char* value(const ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
sensor_msgs/Image img_data\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.img_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRobotPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::relocalization_sweeper::GetRobotPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "img_data: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RELOCALIZATION_SWEEPER_MESSAGE_GETROBOTPOSEREQUEST_H
