// Generated by gencpp from file relocalization_sweeper/GetRobotPose.msg
// DO NOT EDIT!


#ifndef RELOCALIZATION_SWEEPER_MESSAGE_GETROBOTPOSE_H
#define RELOCALIZATION_SWEEPER_MESSAGE_GETROBOTPOSE_H

#include <ros/service_traits.h>


#include <relocalization_sweeper/GetRobotPoseRequest.h>
#include <relocalization_sweeper/GetRobotPoseResponse.h>


namespace relocalization_sweeper
{

struct GetRobotPose
{

typedef GetRobotPoseRequest Request;
typedef GetRobotPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRobotPose
} // namespace relocalization_sweeper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::relocalization_sweeper::GetRobotPose > {
  static const char* value()
  {
    return "e2d88b1ab1ddd4e7df90d778b40332bd";
  }

  static const char* value(const ::relocalization_sweeper::GetRobotPose&) { return value(); }
};

template<>
struct DataType< ::relocalization_sweeper::GetRobotPose > {
  static const char* value()
  {
    return "relocalization_sweeper/GetRobotPose";
  }

  static const char* value(const ::relocalization_sweeper::GetRobotPose&) { return value(); }
};


// service_traits::MD5Sum< ::relocalization_sweeper::GetRobotPoseRequest> should match 
// service_traits::MD5Sum< ::relocalization_sweeper::GetRobotPose > 
template<>
struct MD5Sum< ::relocalization_sweeper::GetRobotPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::relocalization_sweeper::GetRobotPose >::value();
  }
  static const char* value(const ::relocalization_sweeper::GetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::relocalization_sweeper::GetRobotPoseRequest> should match 
// service_traits::DataType< ::relocalization_sweeper::GetRobotPose > 
template<>
struct DataType< ::relocalization_sweeper::GetRobotPoseRequest>
{
  static const char* value()
  {
    return DataType< ::relocalization_sweeper::GetRobotPose >::value();
  }
  static const char* value(const ::relocalization_sweeper::GetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::relocalization_sweeper::GetRobotPoseResponse> should match 
// service_traits::MD5Sum< ::relocalization_sweeper::GetRobotPose > 
template<>
struct MD5Sum< ::relocalization_sweeper::GetRobotPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::relocalization_sweeper::GetRobotPose >::value();
  }
  static const char* value(const ::relocalization_sweeper::GetRobotPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::relocalization_sweeper::GetRobotPoseResponse> should match 
// service_traits::DataType< ::relocalization_sweeper::GetRobotPose > 
template<>
struct DataType< ::relocalization_sweeper::GetRobotPoseResponse>
{
  static const char* value()
  {
    return DataType< ::relocalization_sweeper::GetRobotPose >::value();
  }
  static const char* value(const ::relocalization_sweeper::GetRobotPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RELOCALIZATION_SWEEPER_MESSAGE_GETROBOTPOSE_H
