// Generated by gencpp from file coverage_path_planning/GetCoveragePath.msg
// DO NOT EDIT!


#ifndef COVERAGE_PATH_PLANNING_MESSAGE_GETCOVERAGEPATH_H
#define COVERAGE_PATH_PLANNING_MESSAGE_GETCOVERAGEPATH_H

#include <ros/service_traits.h>


#include <coverage_path_planning/GetCoveragePathRequest.h>
#include <coverage_path_planning/GetCoveragePathResponse.h>


namespace coverage_path_planning
{

struct GetCoveragePath
{

typedef GetCoveragePathRequest Request;
typedef GetCoveragePathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCoveragePath
} // namespace coverage_path_planning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::coverage_path_planning::GetCoveragePath > {
  static const char* value()
  {
    return "942df67a0deefe8bfb22ef78e1504921";
  }

  static const char* value(const ::coverage_path_planning::GetCoveragePath&) { return value(); }
};

template<>
struct DataType< ::coverage_path_planning::GetCoveragePath > {
  static const char* value()
  {
    return "coverage_path_planning/GetCoveragePath";
  }

  static const char* value(const ::coverage_path_planning::GetCoveragePath&) { return value(); }
};


// service_traits::MD5Sum< ::coverage_path_planning::GetCoveragePathRequest> should match 
// service_traits::MD5Sum< ::coverage_path_planning::GetCoveragePath > 
template<>
struct MD5Sum< ::coverage_path_planning::GetCoveragePathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::coverage_path_planning::GetCoveragePath >::value();
  }
  static const char* value(const ::coverage_path_planning::GetCoveragePathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::coverage_path_planning::GetCoveragePathRequest> should match 
// service_traits::DataType< ::coverage_path_planning::GetCoveragePath > 
template<>
struct DataType< ::coverage_path_planning::GetCoveragePathRequest>
{
  static const char* value()
  {
    return DataType< ::coverage_path_planning::GetCoveragePath >::value();
  }
  static const char* value(const ::coverage_path_planning::GetCoveragePathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::coverage_path_planning::GetCoveragePathResponse> should match 
// service_traits::MD5Sum< ::coverage_path_planning::GetCoveragePath > 
template<>
struct MD5Sum< ::coverage_path_planning::GetCoveragePathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::coverage_path_planning::GetCoveragePath >::value();
  }
  static const char* value(const ::coverage_path_planning::GetCoveragePathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::coverage_path_planning::GetCoveragePathResponse> should match 
// service_traits::DataType< ::coverage_path_planning::GetCoveragePath > 
template<>
struct DataType< ::coverage_path_planning::GetCoveragePathResponse>
{
  static const char* value()
  {
    return DataType< ::coverage_path_planning::GetCoveragePath >::value();
  }
  static const char* value(const ::coverage_path_planning::GetCoveragePathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COVERAGE_PATH_PLANNING_MESSAGE_GETCOVERAGEPATH_H
