// Generated by gencpp from file coverage_path_planning/GetCoveragePathRequest.msg
// DO NOT EDIT!


#ifndef COVERAGE_PATH_PLANNING_MESSAGE_GETCOVERAGEPATHREQUEST_H
#define COVERAGE_PATH_PLANNING_MESSAGE_GETCOVERAGEPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>
#include <nav_msgs/OccupancyGrid.h>

namespace coverage_path_planning
{
template <class ContainerAllocator>
struct GetCoveragePathRequest_
{
  typedef GetCoveragePathRequest_<ContainerAllocator> Type;

  GetCoveragePathRequest_()
    : start()
    , goal()
    , erosion_radius(0.0)
    , robot_radius(0.0)
    , occupancy_threshold(0)
    , map()  {
    }
  GetCoveragePathRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , goal(_alloc)
    , erosion_radius(0.0)
    , robot_radius(0.0)
    , occupancy_threshold(0)
    , map(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef double _erosion_radius_type;
  _erosion_radius_type erosion_radius;

   typedef double _robot_radius_type;
  _robot_radius_type robot_radius;

   typedef int8_t _occupancy_threshold_type;
  _occupancy_threshold_type occupancy_threshold;

   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _map_type;
  _map_type map;





  typedef boost::shared_ptr< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCoveragePathRequest_

typedef ::coverage_path_planning::GetCoveragePathRequest_<std::allocator<void> > GetCoveragePathRequest;

typedef boost::shared_ptr< ::coverage_path_planning::GetCoveragePathRequest > GetCoveragePathRequestPtr;
typedef boost::shared_ptr< ::coverage_path_planning::GetCoveragePathRequest const> GetCoveragePathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace coverage_path_planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4219cf242dbc3b080f93747a5b0ea84";
  }

  static const char* value(const ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4219cf242dbc3b0ULL;
  static const uint64_t static_value2 = 0x80f93747a5b0ea84ULL;
};

template<class ContainerAllocator>
struct DataType< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coverage_path_planning/GetCoveragePathRequest";
  }

  static const char* value(const ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
geometry_msgs/PoseStamped start\n\
\n\
\n\
geometry_msgs/PoseStamped goal\n\
\n\
\n\
\n\
float64 erosion_radius\n\
\n\
\n\
\n\
float64 robot_radius\n\
\n\
\n\
\n\
int8 occupancy_threshold\n\
\n\
nav_msgs/OccupancyGrid map\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: nav_msgs/OccupancyGrid\n\
# This represents a 2-D grid map, in which each cell represents the probability of\n\
# occupancy.\n\
\n\
Header header \n\
\n\
#MetaData for the map\n\
MapMetaData info\n\
\n\
# The map data, in row-major order, starting with (0,0).  Occupancy\n\
# probabilities are in the range [0,100].  Unknown is -1.\n\
int8[] data\n\
\n\
================================================================================\n\
MSG: nav_msgs/MapMetaData\n\
# This hold basic information about the characterists of the OccupancyGrid\n\
\n\
# The time at which the map was loaded\n\
time map_load_time\n\
# The map resolution [m/cell]\n\
float32 resolution\n\
# Map width [cells]\n\
uint32 width\n\
# Map height [cells]\n\
uint32 height\n\
# The origin of the map [m, m, rad].  This is the real-world pose of the\n\
# cell (0,0) in the map.\n\
geometry_msgs/Pose origin\n\
";
  }

  static const char* value(const ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.goal);
      stream.next(m.erosion_radius);
      stream.next(m.robot_radius);
      stream.next(m.occupancy_threshold);
      stream.next(m.map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCoveragePathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coverage_path_planning::GetCoveragePathRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "erosion_radius: ";
    Printer<double>::stream(s, indent + "  ", v.erosion_radius);
    s << indent << "robot_radius: ";
    Printer<double>::stream(s, indent + "  ", v.robot_radius);
    s << indent << "occupancy_threshold: ";
    Printer<int8_t>::stream(s, indent + "  ", v.occupancy_threshold);
    s << indent << "map: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COVERAGE_PATH_PLANNING_MESSAGE_GETCOVERAGEPATHREQUEST_H
