#ifndef __FACEEXPRESSIONSSTREAMEXT_H__
#define __FACEEXPRESSIONSSTREAMEXT_H__

#include "StreamsExport.h"

#include "FaceExpressionsStream.h"
#include <functional>
#include <map>

#ifdef _MSC_VER
#pragma warning(disable: 4251)
#endif

namespace InuDev 
{
    struct CVideoInitParams;
    struct CSensorParamsExt;

    ////////////////////////////////////////////////////////////////////////
    /// \brief   Extended face expressions frame.
    ///   
    /// Responsibilities: 
    ///      1. Implements ISerializableFrame interface.
    ///
    ////////////////////////////////////////////////////////////////////////
    struct CFaceExpressionsFrameExt  : public CFaceExpressionsFrame
    {

        CPoint2D      FaceRectPos;

        CPoint2D      FaceRectSize;
        
        CFaceExpressionsFrameExt() : CFaceExpressionsFrame(), FaceRectPos(), FaceRectSize() {}

#ifndef _MSC_VER
        CFaceExpressionsFrameExt(const CFaceExpressionsFrameExt&) = default;
        CFaceExpressionsFrameExt& operator=(const CFaceExpressionsFrameExt&) = default;
#endif

    };


    ////////////////////////////////////////////////////////////////////////
    /// \brief   Extended Interface for Face expressions recognition service.
    /// 
    /// Responsibilities: 
    ///      1. Set service parameters
    ///
    ////////////////////////////////////////////////////////////////////////
    class CFaceExpressionsStreamExt : public CFaceExpressionsStream 
    {

    public:
        using CFaceExpressionsStream::GetFrame;

        CFaceExpressionsStreamExt() : CFaceExpressionsStream() {}
        virtual ~CFaceExpressionsStreamExt() {}

        //Extended methods
        virtual CInuError  GetFrame(CFaceExpressionsFrameExt& headInfo, unsigned int iTimeout = FPS_BASED_TIMEOUT) = 0;

        /// \brief    Set service parameters
        /// 
        /// Must be called before starting the service
        /// \param[in] iAdvancedFeatures    Track advanced features like glasses, gender and advanced expressions.
        /// \return InuDev::CInuError    error generated by IAF.
        virtual CInuError  SetParams(bool iAdvancedFeatures) = 0;

        /// \brief    Set video parameters
        /// 
        /// Must be called before starting any service uses video
        /// \param[in] params    Video initialization parameters
        /// \return InuDev::CInuError    error generated by IAF.
        virtual CInuError  SetVideoParams(const CVideoInitParams& params) = 0;

    };
}

#endif // __FACEEXPRESSIONSSTREAMEXT_H__
