// Generated by gencpp from file potential_exploration/GetNextFrontier.msg
// DO NOT EDIT!


#ifndef POTENTIAL_EXPLORATION_MESSAGE_GETNEXTFRONTIER_H
#define POTENTIAL_EXPLORATION_MESSAGE_GETNEXTFRONTIER_H

#include <ros/service_traits.h>


#include <potential_exploration/GetNextFrontierRequest.h>
#include <potential_exploration/GetNextFrontierResponse.h>


namespace potential_exploration
{

struct GetNextFrontier
{

typedef GetNextFrontierRequest Request;
typedef GetNextFrontierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNextFrontier
} // namespace potential_exploration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::potential_exploration::GetNextFrontier > {
  static const char* value()
  {
    return "64ecba68ae46f9eaced9d50f64329405";
  }

  static const char* value(const ::potential_exploration::GetNextFrontier&) { return value(); }
};

template<>
struct DataType< ::potential_exploration::GetNextFrontier > {
  static const char* value()
  {
    return "potential_exploration/GetNextFrontier";
  }

  static const char* value(const ::potential_exploration::GetNextFrontier&) { return value(); }
};


// service_traits::MD5Sum< ::potential_exploration::GetNextFrontierRequest> should match 
// service_traits::MD5Sum< ::potential_exploration::GetNextFrontier > 
template<>
struct MD5Sum< ::potential_exploration::GetNextFrontierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::potential_exploration::GetNextFrontier >::value();
  }
  static const char* value(const ::potential_exploration::GetNextFrontierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::potential_exploration::GetNextFrontierRequest> should match 
// service_traits::DataType< ::potential_exploration::GetNextFrontier > 
template<>
struct DataType< ::potential_exploration::GetNextFrontierRequest>
{
  static const char* value()
  {
    return DataType< ::potential_exploration::GetNextFrontier >::value();
  }
  static const char* value(const ::potential_exploration::GetNextFrontierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::potential_exploration::GetNextFrontierResponse> should match 
// service_traits::MD5Sum< ::potential_exploration::GetNextFrontier > 
template<>
struct MD5Sum< ::potential_exploration::GetNextFrontierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::potential_exploration::GetNextFrontier >::value();
  }
  static const char* value(const ::potential_exploration::GetNextFrontierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::potential_exploration::GetNextFrontierResponse> should match 
// service_traits::DataType< ::potential_exploration::GetNextFrontier > 
template<>
struct DataType< ::potential_exploration::GetNextFrontierResponse>
{
  static const char* value()
  {
    return DataType< ::potential_exploration::GetNextFrontier >::value();
  }
  static const char* value(const ::potential_exploration::GetNextFrontierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POTENTIAL_EXPLORATION_MESSAGE_GETNEXTFRONTIER_H
