// Generated by gencpp from file potential_exploration/GetNextFrontierResponse.msg
// DO NOT EDIT!


#ifndef POTENTIAL_EXPLORATION_MESSAGE_GETNEXTFRONTIERRESPONSE_H
#define POTENTIAL_EXPLORATION_MESSAGE_GETNEXTFRONTIERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace potential_exploration
{
template <class ContainerAllocator>
struct GetNextFrontierResponse_
{
  typedef GetNextFrontierResponse_<ContainerAllocator> Type;

  GetNextFrontierResponse_()
    : goal()  {
    }
  GetNextFrontierResponse_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetNextFrontierResponse_

typedef ::potential_exploration::GetNextFrontierResponse_<std::allocator<void> > GetNextFrontierResponse;

typedef boost::shared_ptr< ::potential_exploration::GetNextFrontierResponse > GetNextFrontierResponsePtr;
typedef boost::shared_ptr< ::potential_exploration::GetNextFrontierResponse const> GetNextFrontierResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace potential_exploration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'potential_exploration': ['/home/firefly/potential_exploration_ros/src/potential_exploration/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da4877bfa97b4954b860aa1c3243000a";
  }

  static const char* value(const ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda4877bfa97b4954ULL;
  static const uint64_t static_value2 = 0xb860aa1c3243000aULL;
};

template<class ContainerAllocator>
struct DataType< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "potential_exploration/GetNextFrontierResponse";
  }

  static const char* value(const ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray goal\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNextFrontierResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::potential_exploration::GetNextFrontierResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POTENTIAL_EXPLORATION_MESSAGE_GETNEXTFRONTIERRESPONSE_H
