// Generated by gencpp from file potential_exploration/GetNextFrontierRequest.msg
// DO NOT EDIT!


#ifndef POTENTIAL_EXPLORATION_MESSAGE_GETNEXTFRONTIERREQUEST_H
#define POTENTIAL_EXPLORATION_MESSAGE_GETNEXTFRONTIERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace potential_exploration
{
template <class ContainerAllocator>
struct GetNextFrontierRequest_
{
  typedef GetNextFrontierRequest_<ContainerAllocator> Type;

  GetNextFrontierRequest_()
    : n_frontier(0)  {
    }
  GetNextFrontierRequest_(const ContainerAllocator& _alloc)
    : n_frontier(0)  {
  (void)_alloc;
    }



   typedef int64_t _n_frontier_type;
  _n_frontier_type n_frontier;





  typedef boost::shared_ptr< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetNextFrontierRequest_

typedef ::potential_exploration::GetNextFrontierRequest_<std::allocator<void> > GetNextFrontierRequest;

typedef boost::shared_ptr< ::potential_exploration::GetNextFrontierRequest > GetNextFrontierRequestPtr;
typedef boost::shared_ptr< ::potential_exploration::GetNextFrontierRequest const> GetNextFrontierRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace potential_exploration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'potential_exploration': ['/home/firefly/potential_exploration_ros/src/potential_exploration/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d64ce4d9400a45126b7f2cfeda97fbc";
  }

  static const char* value(const ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d64ce4d9400a451ULL;
  static const uint64_t static_value2 = 0x26b7f2cfeda97fbcULL;
};

template<class ContainerAllocator>
struct DataType< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "potential_exploration/GetNextFrontierRequest";
  }

  static const char* value(const ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int64 n_frontier\n\
";
  }

  static const char* value(const ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.n_frontier);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetNextFrontierRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::potential_exploration::GetNextFrontierRequest_<ContainerAllocator>& v)
  {
    s << indent << "n_frontier: ";
    Printer<int64_t>::stream(s, indent + "  ", v.n_frontier);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POTENTIAL_EXPLORATION_MESSAGE_GETNEXTFRONTIERREQUEST_H
