// Generated by gencpp from file potential_exploration/PotentialPlannerResponse.msg
// DO NOT EDIT!


#ifndef POTENTIAL_EXPLORATION_MESSAGE_POTENTIALPLANNERRESPONSE_H
#define POTENTIAL_EXPLORATION_MESSAGE_POTENTIALPLANNERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace potential_exploration
{
template <class ContainerAllocator>
struct PotentialPlannerResponse_
{
  typedef PotentialPlannerResponse_<ContainerAllocator> Type;

  PotentialPlannerResponse_()
    : poses()  {
    }
  PotentialPlannerResponse_(const ContainerAllocator& _alloc)
    : poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PotentialPlannerResponse_

typedef ::potential_exploration::PotentialPlannerResponse_<std::allocator<void> > PotentialPlannerResponse;

typedef boost::shared_ptr< ::potential_exploration::PotentialPlannerResponse > PotentialPlannerResponsePtr;
typedef boost::shared_ptr< ::potential_exploration::PotentialPlannerResponse const> PotentialPlannerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace potential_exploration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'potential_exploration': ['/home/firefly/potential_exploration_ros/src/potential_exploration/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31a710d661541413a823a4591402c488";
  }

  static const char* value(const ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31a710d661541413ULL;
  static const uint64_t static_value2 = 0xa823a4591402c488ULL;
};

template<class ContainerAllocator>
struct DataType< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "potential_exploration/PotentialPlannerResponse";
  }

  static const char* value(const ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D[] poses\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PotentialPlannerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::potential_exploration::PotentialPlannerResponse_<ContainerAllocator>& v)
  {
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POTENTIAL_EXPLORATION_MESSAGE_POTENTIALPLANNERRESPONSE_H
