// Generated by gencpp from file potential_exploration/PotentialPlanner.msg
// DO NOT EDIT!


#ifndef POTENTIAL_EXPLORATION_MESSAGE_POTENTIALPLANNER_H
#define POTENTIAL_EXPLORATION_MESSAGE_POTENTIALPLANNER_H

#include <ros/service_traits.h>


#include <potential_exploration/PotentialPlannerRequest.h>
#include <potential_exploration/PotentialPlannerResponse.h>


namespace potential_exploration
{

struct PotentialPlanner
{

typedef PotentialPlannerRequest Request;
typedef PotentialPlannerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PotentialPlanner
} // namespace potential_exploration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::potential_exploration::PotentialPlanner > {
  static const char* value()
  {
    return "212e230aa5de14ba1f6a422ed748ee98";
  }

  static const char* value(const ::potential_exploration::PotentialPlanner&) { return value(); }
};

template<>
struct DataType< ::potential_exploration::PotentialPlanner > {
  static const char* value()
  {
    return "potential_exploration/PotentialPlanner";
  }

  static const char* value(const ::potential_exploration::PotentialPlanner&) { return value(); }
};


// service_traits::MD5Sum< ::potential_exploration::PotentialPlannerRequest> should match 
// service_traits::MD5Sum< ::potential_exploration::PotentialPlanner > 
template<>
struct MD5Sum< ::potential_exploration::PotentialPlannerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::potential_exploration::PotentialPlanner >::value();
  }
  static const char* value(const ::potential_exploration::PotentialPlannerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::potential_exploration::PotentialPlannerRequest> should match 
// service_traits::DataType< ::potential_exploration::PotentialPlanner > 
template<>
struct DataType< ::potential_exploration::PotentialPlannerRequest>
{
  static const char* value()
  {
    return DataType< ::potential_exploration::PotentialPlanner >::value();
  }
  static const char* value(const ::potential_exploration::PotentialPlannerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::potential_exploration::PotentialPlannerResponse> should match 
// service_traits::MD5Sum< ::potential_exploration::PotentialPlanner > 
template<>
struct MD5Sum< ::potential_exploration::PotentialPlannerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::potential_exploration::PotentialPlanner >::value();
  }
  static const char* value(const ::potential_exploration::PotentialPlannerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::potential_exploration::PotentialPlannerResponse> should match 
// service_traits::DataType< ::potential_exploration::PotentialPlanner > 
template<>
struct DataType< ::potential_exploration::PotentialPlannerResponse>
{
  static const char* value()
  {
    return DataType< ::potential_exploration::PotentialPlanner >::value();
  }
  static const char* value(const ::potential_exploration::PotentialPlannerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POTENTIAL_EXPLORATION_MESSAGE_POTENTIALPLANNER_H
