// Generated by gencpp from file potential_exploration/PotentialPlannerRequest.msg
// DO NOT EDIT!


#ifndef POTENTIAL_EXPLORATION_MESSAGE_POTENTIALPLANNERREQUEST_H
#define POTENTIAL_EXPLORATION_MESSAGE_POTENTIALPLANNERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace potential_exploration
{
template <class ContainerAllocator>
struct PotentialPlannerRequest_
{
  typedef PotentialPlannerRequest_<ContainerAllocator> Type;

  PotentialPlannerRequest_()
    : goal_state_x(0.0)
    , goal_state_y(0.0)  {
    }
  PotentialPlannerRequest_(const ContainerAllocator& _alloc)
    : goal_state_x(0.0)
    , goal_state_y(0.0)  {
  (void)_alloc;
    }



   typedef float _goal_state_x_type;
  _goal_state_x_type goal_state_x;

   typedef float _goal_state_y_type;
  _goal_state_y_type goal_state_y;





  typedef boost::shared_ptr< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PotentialPlannerRequest_

typedef ::potential_exploration::PotentialPlannerRequest_<std::allocator<void> > PotentialPlannerRequest;

typedef boost::shared_ptr< ::potential_exploration::PotentialPlannerRequest > PotentialPlannerRequestPtr;
typedef boost::shared_ptr< ::potential_exploration::PotentialPlannerRequest const> PotentialPlannerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace potential_exploration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'potential_exploration': ['/home/firefly/potential_exploration_ros/src/potential_exploration/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3eec92e9931d840466bf38ee4708656f";
  }

  static const char* value(const ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3eec92e9931d8404ULL;
  static const uint64_t static_value2 = 0x66bf38ee4708656fULL;
};

template<class ContainerAllocator>
struct DataType< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "potential_exploration/PotentialPlannerRequest";
  }

  static const char* value(const ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32 goal_state_x\n\
float32 goal_state_y\n\
";
  }

  static const char* value(const ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_state_x);
      stream.next(m.goal_state_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PotentialPlannerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::potential_exploration::PotentialPlannerRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal_state_x: ";
    Printer<float>::stream(s, indent + "  ", v.goal_state_x);
    s << indent << "goal_state_y: ";
    Printer<float>::stream(s, indent + "  ", v.goal_state_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POTENTIAL_EXPLORATION_MESSAGE_POTENTIALPLANNERREQUEST_H
