// Generated by gencpp from file potential_exploration/WaypointPropositionResponse.msg
// DO NOT EDIT!


#ifndef POTENTIAL_EXPLORATION_MESSAGE_WAYPOINTPROPOSITIONRESPONSE_H
#define POTENTIAL_EXPLORATION_MESSAGE_WAYPOINTPROPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace potential_exploration
{
template <class ContainerAllocator>
struct WaypointPropositionResponse_
{
  typedef WaypointPropositionResponse_<ContainerAllocator> Type;

  WaypointPropositionResponse_()
    : accepted(false)  {
    }
  WaypointPropositionResponse_(const ContainerAllocator& _alloc)
    : accepted(false)  {
  (void)_alloc;
    }



   typedef uint8_t _accepted_type;
  _accepted_type accepted;





  typedef boost::shared_ptr< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointPropositionResponse_

typedef ::potential_exploration::WaypointPropositionResponse_<std::allocator<void> > WaypointPropositionResponse;

typedef boost::shared_ptr< ::potential_exploration::WaypointPropositionResponse > WaypointPropositionResponsePtr;
typedef boost::shared_ptr< ::potential_exploration::WaypointPropositionResponse const> WaypointPropositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace potential_exploration

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'potential_exploration': ['/home/firefly/potential_exploration_ros/src/potential_exploration/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ea39b897cc8620c46aaa14cb60920cd";
  }

  static const char* value(const ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ea39b897cc8620cULL;
  static const uint64_t static_value2 = 0x46aaa14cb60920cdULL;
};

template<class ContainerAllocator>
struct DataType< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "potential_exploration/WaypointPropositionResponse";
  }

  static const char* value(const ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool accepted\n\
";
  }

  static const char* value(const ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accepted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointPropositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::potential_exploration::WaypointPropositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "accepted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.accepted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POTENTIAL_EXPLORATION_MESSAGE_WAYPOINTPROPOSITIONRESPONSE_H
