// Generated by gencpp from file potential_exploration/WaypointProposition.msg
// DO NOT EDIT!


#ifndef POTENTIAL_EXPLORATION_MESSAGE_WAYPOINTPROPOSITION_H
#define POTENTIAL_EXPLORATION_MESSAGE_WAYPOINTPROPOSITION_H

#include <ros/service_traits.h>


#include <potential_exploration/WaypointPropositionRequest.h>
#include <potential_exploration/WaypointPropositionResponse.h>


namespace potential_exploration
{

struct WaypointProposition
{

typedef WaypointPropositionRequest Request;
typedef WaypointPropositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WaypointProposition
} // namespace potential_exploration


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::potential_exploration::WaypointProposition > {
  static const char* value()
  {
    return "250895dd0b8198b18e2f744834d53b21";
  }

  static const char* value(const ::potential_exploration::WaypointProposition&) { return value(); }
};

template<>
struct DataType< ::potential_exploration::WaypointProposition > {
  static const char* value()
  {
    return "potential_exploration/WaypointProposition";
  }

  static const char* value(const ::potential_exploration::WaypointProposition&) { return value(); }
};


// service_traits::MD5Sum< ::potential_exploration::WaypointPropositionRequest> should match 
// service_traits::MD5Sum< ::potential_exploration::WaypointProposition > 
template<>
struct MD5Sum< ::potential_exploration::WaypointPropositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::potential_exploration::WaypointProposition >::value();
  }
  static const char* value(const ::potential_exploration::WaypointPropositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::potential_exploration::WaypointPropositionRequest> should match 
// service_traits::DataType< ::potential_exploration::WaypointProposition > 
template<>
struct DataType< ::potential_exploration::WaypointPropositionRequest>
{
  static const char* value()
  {
    return DataType< ::potential_exploration::WaypointProposition >::value();
  }
  static const char* value(const ::potential_exploration::WaypointPropositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::potential_exploration::WaypointPropositionResponse> should match 
// service_traits::MD5Sum< ::potential_exploration::WaypointProposition > 
template<>
struct MD5Sum< ::potential_exploration::WaypointPropositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::potential_exploration::WaypointProposition >::value();
  }
  static const char* value(const ::potential_exploration::WaypointPropositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::potential_exploration::WaypointPropositionResponse> should match 
// service_traits::DataType< ::potential_exploration::WaypointProposition > 
template<>
struct DataType< ::potential_exploration::WaypointPropositionResponse>
{
  static const char* value()
  {
    return DataType< ::potential_exploration::WaypointProposition >::value();
  }
  static const char* value(const ::potential_exploration::WaypointPropositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POTENTIAL_EXPLORATION_MESSAGE_WAYPOINTPROPOSITION_H
